"""
reports/report_generator.py
-----------------------------
Turns a stored scan (and its findings) into shareable report files:
a formatted PDF (via reportlab) and a flat CSV (via pandas), both
including the automated exploitability assessment from
utils/threat_intel.py.

Security concept demonstrated:
    Report generation is read-only and entirely local: it only reads
    already-stored findings from SQLite and writes a file to disk, it
    never touches the network. Keeping this separate from scanner/ and
    database/ keeps the "who can make outbound requests" surface (see
    scanner/scanner.py's docstring) limited to a single module even as
    the app grows more features.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from utils.logger import get_logger
from utils.threat_intel import assess_scan

logger = get_logger(__name__)

_RISK_COLORS = {
    "High": "#D64545",
    "Medium": "#E0A030",
    "Low": "#3B8ED0",
}


def _styles() -> dict:
    base = getSampleStyleSheet()
    base.add(
        ParagraphStyle(
            name="ReportTitle",
            parent=base["Title"],
            fontSize=20,
            spaceAfter=4,
        )
    )
    base.add(
        ParagraphStyle(
            name="SectionHeading",
            parent=base["Heading2"],
            spaceBefore=16,
            spaceAfter=6,
        )
    )
    base.add(
        ParagraphStyle(
            name="Body",
            parent=base["BodyText"],
            fontSize=9.5,
            leading=13,
            alignment=TA_LEFT,
        )
    )
    return base


def generate_pdf_report(scan_row, findings: list, output_path: str | Path) -> Path:
    """
    Build a PDF report for one scan.

    Args:
        scan_row: a `scans` table row (target_url, scan_date, security_score,
            high_count, medium_count, low_count).
        findings: list of `findings` table rows for that scan (each also
            carrying target_url/scan_date from the JOIN).
        output_path: where to write the .pdf file.

    Returns:
        The Path the PDF was written to.
    """
    output_path = Path(output_path)
    styles = _styles()
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=LETTER,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
        leftMargin=0.6 * inch,
        rightMargin=0.6 * inch,
    )

    assessment = assess_scan(findings)
    story = []

    story.append(Paragraph("OWASP Top 10 Security Assessment Report", styles["ReportTitle"]))
    story.append(
        Paragraph(
            f"Target: <b>{scan_row['target_url']}</b> &nbsp;|&nbsp; "
            f"Scan date: {scan_row['scan_date']} &nbsp;|&nbsp; "
            f"Security score: <b>{scan_row['security_score']}%</b>",
            styles["Body"],
        )
    )
    story.append(Spacer(1, 10))

    # --- Summary table ---
    summary_data = [
        ["High", "Medium", "Low", "Likely Exploitable"],
        [
            str(scan_row["high_count"]),
            str(scan_row["medium_count"]),
            str(scan_row["low_count"]),
            str(assessment["likely_exploitable_count"]),
        ],
    ]
    summary_table = Table(summary_data, colWidths=[1.6 * inch] * 4)
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2b2b2b")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(summary_table)
    story.append(Spacer(1, 4))
    story.append(
        Paragraph(
            "This report is generated by safe, passive checks only. "
            "'Educational use only - authorized targets only.'",
            ParagraphStyle(name="Disclaimer", fontSize=8, textColor=colors.grey, parent=styles["Body"]),
        )
    )

    # --- Automated exploitability assessment section ---
    story.append(Paragraph("Automated Exploitability Assessment", styles["SectionHeading"]))
    story.append(
        Paragraph(
            "Each finding below is mapped to the kind of attack it makes "
            "easier, ranked from most to least likely to be practically "
            "exploitable, based on well-known OWASP Top 10 guidance.",
            styles["Body"],
        )
    )
    story.append(Spacer(1, 6))

    for item in assessment["assessed_findings"]:
        risk_color = _RISK_COLORS.get(item["risk_level"], "#888888")
        block = [
            Paragraph(
                f'<font color="{risk_color}"><b>[{item["risk_level"].upper()}]</b></font> '
                f'{item["title"]} &nbsp;&nbsp;'
                f'<font color="#555555">— {item["exploitability"].value}</font>',
                styles["Body"],
            ),
            Paragraph(f'<i>{item["owasp_category"]}</i>', styles["Body"]),
            Paragraph(f'<b>Possible attack:</b> {item["attack_name"]} — {item["how_it_works"]}', styles["Body"]),
            Paragraph(f'<b>Protection:</b> {item["protection"]}', styles["Body"]),
            Spacer(1, 10),
        ]
        story.append(KeepTogether(block))

    if not assessment["assessed_findings"]:
        story.append(Paragraph("No findings were recorded for this scan.", styles["Body"]))

    doc.build(story)
    logger.info("Generated PDF report for scan at %s -> %s", scan_row["target_url"], output_path)
    return output_path


def generate_csv_report(findings: list, output_path: str | Path) -> Path:
    """
    Export findings (plus their automated assessment) to a flat CSV,
    one row per finding - useful for spreadsheets or ticket imports.
    """
    output_path = Path(output_path)
    assessment = assess_scan(findings)

    rows = []
    for item in assessment["assessed_findings"]:
        rows.append(
            {
                "risk_level": item["risk_level"],
                "owasp_category": item["owasp_category"],
                "title": item["title"],
                "exploitability": item["exploitability"].value,
                "likely_attack": item["attack_name"],
                "how_it_works": item["how_it_works"],
                "protection": item["protection"],
            }
        )

    df = pd.DataFrame(
        rows,
        columns=[
            "risk_level",
            "owasp_category",
            "title",
            "exploitability",
            "likely_attack",
            "how_it_works",
            "protection",
        ],
    )
    df.to_csv(output_path, index=False)
    logger.info("Generated CSV report with %d findings -> %s", len(rows), output_path)
    return output_path
